Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'

-- Deliveries
Config.ShopsInvJsonFile = './json/shops-inventory.json'
Config.TruckDeposit = 125
Config.MaxDeliveries = 20
Config.DeliveryPrice = 500
Config.RewardItem = 'cryptostick'
Config.Fuel = 'LegacyFuel'

Config.DeliveryLocations = {
    ['main'] = { label = 'GO Postal', coords = vector4(69.0862, 127.6753, 79.2123, 156.7736) },
    ['vehicleWithdraw'] = vector4(71.9318, 120.8389, 79.0823, 160.5110),
    ['vehicleDeposit'] = vector3(62.7282, 124.9846, 79.0926),
    ['stores'] = {} -- auto generated
}

Config.Vehicles = {
    ['boxville2'] = { ['label'] = 'Boxville StepVan', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
}

Config.Products = {
    ['stores'] = {
        {name = 'tosti',         price = 20,   amount = 50,   info = {}, type = 'item'},
        {name = 'water_bottle',  price = 20,   amount = 50,   info = {}, type = 'item'},
        {name = 'kurkakola',     price = 20,   amount = 50,   info = {}, type = 'item'},
        {name = 'twerks_candy',  price = 20,   amount = 50,   info = {}, type = 'item'},
        {name = 'snikkel_candy', price = 20,   amount = 50,   info = {}, type = 'item'},
        {name = 'sandwich',      price = 20,   amount = 50,   info = {}, type = 'item'},
        {name = 'beer',          price = 70,   amount = 50,   info = {}, type = 'item'},
        {name = 'whiskey',       price = 100,  amount = 50,   info = {}, type = 'item'},
        {name = 'vodka',         price = 120,  amount = 50,   info = {}, type = 'item'},
        {name = 'bandage',       price = 1000, amount = 50,   info = {}, type = 'item'},
        {name = 'lighter',       price = 20,   amount = 50,   info = {}, type = 'item'},
        {name = 'rolling_paper', price = 20,   amount = 5000, info = {}, type = 'item'},
        {name = 'fps_glasses',   price = 20,   amount = 5000, info = {}, type = 'item'},
        {name = 'bmx',           price = 20000,amount = 20,    info = {}, type = 'item'},
        {name = 'skateboard',    price = 420,  amount = 20,    info = {}, type = 'item'},
        {name = 'clothing_bag',  price = 2,    amount = 20,    info = {}, type = 'item'},
        {name = 'code',          price = 200,  amount = 20,    info = {'fique chiroso'}, type = 'item'},
        
    },
    
    ['liquor'] = {
        {name = 'beer',    price = 7,  amount = 50, info = {}, type = 'item'},
        {name = 'whiskey', price = 100, amount = 50, info = {}, type = 'item'},
        {name = 'vodka',   price = 120, amount = 50, info = {}, type = 'item'},
    },
    ['hardware'] = {
        {name = 'fishingrod',    price = 100, amount = 50,   info = {}, type = 'item'},
        {name = 'fishingbait',   price = 2,   amount = 50,   info = {}, type = 'item'},
        {name = 'trojan_usb',          price = 2000, amount = 50,  info = {}, type = 'item'},
        {name = 'electronickit',          price = 5000, amount = 50,  info = {}, type = 'item'},
        {name = 'lockpick',          price = 200, amount = 50,  info = {}, type = 'item'},
        {name = 'weapon_wrench',     price = 250, amount = 250, info = {}, type = 'item'},
        {name = 'weapon_hammer',     price = 250, amount = 250, info = {}, type = 'item'},
        {name = 'phone',             price = 850, amount = 50,  info = {}, type = 'item'},
        {name = 'radio',             price = 250, amount = 50,  info = {}, type = 'item'},
        {name = 'binoculars',        price = 500,  amount = 50,  info = {}, type = 'item'},
        {name = 'firework1',         price = 50,  amount = 50,  info = {}, type = 'item'},
        {name = 'firework2',         price = 50,  amount = 50,  info = {}, type = 'item'},
        {name = 'firework3',         price = 50,  amount = 50,  info = {}, type = 'item'},
        {name = 'firework4',         price = 50,  amount = 50,  info = {}, type = 'item'},
        {name = 'fitbit',            price = 4000, amount = 150, info = {}, type = 'item'},
        {name = 'cleaningkit',       price = 1500, amount = 150, info = {}, type = 'item'},
        {name = 'repairkit',         price = 500, amount = 50, info = {}, type = 'item'},
        {name = 'advancedrepairkit', price = 5000, amount = 50, info = {}, type = 'item'},
        {name = 'tirerepairkit',     price = 500, amount = 50, info = {}, type = 'item'},
    },
    ['facs'] = {
        {name = 'cleaningkit',       price = 1500, amount = 150, info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'advancedrepairkit', price = 5000, amount = 50, info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'radio',             price = 250, amount = 50,  info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'advancedlockpick',       price = 420, amount = 50, info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'heavyarmor',       price = 0, amount = 50, info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_pistol',        price = 0, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_snspistol',     price = 150000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_vintagepistol', price = 400000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_pistol_mk2', price = 400000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_combatpistol', price = 400000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_stungun', price = 400000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_pistol50', price = 400000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_heavypistol', price = 400000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_vintagepistol', price = 400000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_microsmg', price = 500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_minismg', price = 500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_combatpdw', price = 500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_smg_mk2', price = 500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_pumpshotgun', price = 500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_sawnoffshotgun', price = 500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_pumpshotgun_mk2', price = 500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_raycarbine', price = 5000000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_specialcarbine_mk2', price = 600000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_assaultrifle_mk2', price = 600000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_combatmg_mk2', price = 600000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_gusenberg', price = 600000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_bullpuprifle_mk2', price = 600000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_compactrifle', price = 600000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_militaryrifle', price = 600000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_heavysniper_mk2', price = 1500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_rpg', price = 15000000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_firework', price = 1500000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_hominglauncher', price = 15000000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapon_compactlauncher', price = 15000000, amount = 5,   info = {}, type = 'weapon', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'snp_ammo', price = 1000, amount = 500,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'smg_ammo', price = 1000, amount = 500,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'emp_ammo', price = 1000, amount = 500,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'mg_ammo', price = 1000, amount = 500,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'shotgun_ammo', price = 400, amount = 500,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'rifle_ammo', price = 400, amount = 500,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'pistol_ammo',          price = 0,  amount = 250, info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'clip_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'drum_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'flashlight_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'suppressor_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'smallscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'medscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'largescope_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'holoscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'advscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'nvscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'thermalscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'flat_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'tactical_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'fat_end_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'precision_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'heavy_duty_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'slanted_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'split_end_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'squared_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'bellend_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'barrel_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'grip_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'comp_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'luxuryfinish_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'digicamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'brushcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'woodcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'skullcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'sessantacamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'perseuscamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'leopardcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'zebracamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'geocamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'boomcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'patriotcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_1', price = 15000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_2', price = 15000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_3', price = 15000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_6', price = 15000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_7', price = 15000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_mk2_9', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_mk2_13', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_mk2_16', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_mk2_18', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_mk2_22', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_mk2_23', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_mk2_24', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},
        {name = 'weapontint_mk2_30', price = 150000, amount = 5,   info = {}, type = 'item', requiredGang = {'bahamas', 'lostmc'}},

    },
    ['weedshop'] = {
        {name = 'joint',          price = 10,  amount = 50,   info = {}, type = 'item'},
        {name = 'weapon_poolcue', price = 100, amount = 50,   info = {}, type = 'item'},
        {name = 'weed_nutrition', price = 200,  amount = 50,   info = {}, type = 'item'},
        {name = 'empty_weed_bag', price = 20,   amount = 1000, info = {}, type = 'item'},
        {name = 'rolling_paper',  price = 20,   amount = 1000, info = {}, type = 'item'},
        {name = 'weed_ogkush_seed', price = 200,  amount = 50,   info = {}, type = 'item'},
        {name = 'weed_amnesia_seed', price = 200,  amount = 50,   info = {}, type = 'item'},
        {name = 'weed_skunk_seed', price = 200,  amount = 50,   info = {}, type = 'item'},
        {name = 'weed_ak47_seed', price = 200,  amount = 50,   info = {}, type = 'item'},
        {name = 'weed_purplehaze_seed', price = 200,  amount = 50,   info = {}, type = 'item'},
        {name = 'weed_whitewidow_seed', price = 200,  amount = 50,   info = {}, type = 'item'},
    },
    ['gearshop'] = {
        {name = 'diving_gear', price = 2500, amount = 10, info = {}, type = 'item'},
        {name = 'diving_fill',   price = 200,  amount = 50, info = {}, type = 'item'},
    },
    ['leisureshop'] = {
        {name = 'parachute',   price = 25000, amount = 10, info = {}, type = 'item'},
        {name = 'binoculars',  price = 500,   amount = 50, info = {}, type = 'item'},
        {name = 'diving_gear', price = 2500, amount = 10, info = {}, type = 'item'},
        {name = 'diving_fill', price = 200,  amount = 10, info = {}, type = 'item'},
    },
    ['weapons'] = {
        {name = 'weaponlicense',       price = 50000, amount = 5, info = {}, type = 'item'},
        {name = 'armor',       price = 24000, amount = 50, info = {}, type = 'item'},
        {name = 'heavyarmor',       price = 50000, amount = 50, info = {}, type = 'item'},
        {name = 'weapon_knife',         price = 2500,  amount = 250, info = {}, type = 'weapon'},
        {name = 'weapon_bat',           price = 2500,  amount = 250, info = {}, type = 'weapon'},
        {name = 'weapon_hatchet',       price = 2500,  amount = 250, info = {}, type = 'weapon'},
        {name = 'weapon_pistol',        price = 150000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_snspistol',     price = 150000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_vintagepistol', price = 400000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_pistol_mk2', price = 400000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_combatpistol', price = 400000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_stungun', price = 400000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_pistol50', price = 400000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_heavypistol', price = 400000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_vintagepistol', price = 400000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_microsmg', price = 500000, amount = 5,   info = {}, type = 'weapon' },
        {name = 'weapon_minismg', price = 500000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_combatpdw', price = 500000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_smg_mk2', price = 500000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_pumpshotgun', price = 500000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_sawnoffshotgun', price = 500000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_pumpshotgun_mk2', price = 500000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_raycarbine', price = 5000000, amount = 5,   info = {}, type = 'weapon'},       
        {name = 'weapon_specialcarbine_mk2', price = 600000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_assaultrifle_mk2', price = 600000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_combatmg_mk2', price = 600000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_gusenberg', price = 600000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_bullpuprifle_mk2', price = 600000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_compactrifle', price = 600000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_militaryrifle', price = 600000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_heavysniper_mk2', price = 1500000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_rpg', price = 15000000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_firework', price = 1500000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_hominglauncher', price = 15000000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'weapon_compactlauncher', price = 15000000, amount = 5,   info = {}, type = 'weapon'},
        {name = 'snp_ammo', price = 1000, amount = 500,   info = {}, type = 'item'},
        {name = 'smg_ammo', price = 1000, amount = 500,   info = {}, type = 'item'},
        {name = 'emp_ammo', price = 1000, amount = 500,   info = {}, type = 'item'},
        {name = 'mg_ammo', price = 1000, amount = 500,   info = {}, type = 'item'},
        {name = 'shotgun_ammo', price = 400, amount = 500,   info = {}, type = 'item'},
        {name = 'rifle_ammo', price = 400, amount = 500,   info = {}, type = 'item'},
        {name = 'pistol_ammo',          price = 2500,  amount = 250, info = {}, type = 'item' },
        {name = 'clip_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'drum_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'flashlight_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'suppressor_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'smallscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'medscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'largescope_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'holoscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'advscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'nvscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'thermalscope_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'flat_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'tactical_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'fat_end_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'precision_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'heavy_duty_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'slanted_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'split_end_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'squared_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'bellend_muzzle_brake', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'barrel_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'grip_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'comp_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'luxuryfinish_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'digicamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'brushcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'woodcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'skullcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'sessantacamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'perseuscamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'leopardcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'zebracamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'geocamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'boomcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'patriotcamo_attachment', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_1', price = 15000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_2', price = 15000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_3', price = 15000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_6', price = 15000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_7', price = 15000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_mk2_9', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_mk2_13', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_mk2_16', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_mk2_18', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_mk2_22', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_mk2_23', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_mk2_24', price = 150000, amount = 5,   info = {}, type = 'item'},
        {name = 'weapontint_mk2_30', price = 150000, amount = 5,   info = {}, type = 'item'},


    },
    ['tuning'] = {
        {name = 'advancedrepairkit', price = 5000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_armor',         price = 1000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_brakes',        price = 1500, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_engine',        price = 5000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_suspension',    price = 2000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_transmission',  price = 3000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_turbo',         price = 8000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_interior',      price = 1000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_exterior',      price = 1500, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_wheels',        price = 420, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_neons',         price = 800, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_xenons',        price = 900, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_tint',          price = 600, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'veh_plates',        price = 500, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'nitrous',           price = 5000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = 'tunerlaptop',       price = 1000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = "paint_gun",         price = 1000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = "paint_canister",    price = 3000, amount = 50, info = {}, type = 'item', requiredJob = {'mechanic'}},
        {name = "chameleonpaint_161",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_162",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_163",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_164",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_165",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_166",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_167",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_168",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_169",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_170",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_171",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_172",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_173",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_174",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_175",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_176",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_177",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_178",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_179",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_180",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_181",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_182",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_183",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_184",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_185",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_186",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_187",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_188",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_189",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_190",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_191",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_192",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_193",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_194",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_195",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_196",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_197",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_198",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_199",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_200",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_201",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_202",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_203",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_204",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_205",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_206",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_207",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_208",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_209",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_210",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_211",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_212",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_213",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_214",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_215",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_216",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_217",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_218",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_219",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_220",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_221",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_222",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_223",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_224",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_225",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_226",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_227",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_228",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_229",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_230",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_231",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_232",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_233",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_234",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_235",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_236",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_237",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_238",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_239",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_240",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_241",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "chameleonpaint_242",    price = 666, amount = 50, info = {}, type = 'item'},
        {name = "helm1", price = 5000, amount = 50, info = {}, type = 'item'},
        {name = "helm2", price = 5000, amount = 50, info = {}, type = 'item'},
        {name = "helm3", price = 5000, amount = 50, info = {}, type = 'item'},
        {name = "helm4", price = 5000, amount = 50, info = {}, type = 'item'},
        {name = "helm5", price = 5000, amount = 50, info = {}, type = 'item'},
        {name = "helm6", price = 5000, amount = 50, info = {}, type = 'item'},
        {name = "helm7", price = 5000, amount = 50, info = {}, type = 'item'},
        {name = "helm8", price = 5000, amount = 50, info = {}, type = 'item'},
    },
    ['casino'] = {
        {name = 'casinochips', price = 1, amount = 999999, info = {}, type = 'item'}
    },

    ["petshop"] = {

    {name = 'keepcompanionwesty', price = 500000, amount = 5, info = {}, type = 'item'},
    {name = 'keepcompanioncat', price = 500000, amount = 5, info = {}, type = 'item'},
    {name = 'keepcompanionhusky', price = 500000, amount = 5, info = {}, type = 'item'},
    {name = 'petfood', price = 500, amount = 1000, info = {}, type = 'item'},
    {name = 'collarpet', price = 50000, amount = 50, info = {}, type = 'item'},
    {name = 'firstaidforpet', price = 5000, amount = 50, info = {}, type = 'item'},
    {name = 'petnametag', price = 5000, amount = 50, info = {}, type = 'item'},
    {name = 'petwaterbottleportable', price = 5000, amount = 50, info = {}, type = 'item'},
    {name = 'petgroomingkit', price = 5000, amount = 50, info = {}, type = 'item'},

    },

    ['blackmarket'] = {
        { name = 'security_card_01',  price = 5000, amount = 50 },
        { name = 'security_card_02',  price = 5000, amount = 50 },
        { name = 'advanced_lockpick', price = 5000, amount = 50 },
        { name = 'electronickit',     price = 5000, amount = 50 },
        { name = 'gatecrack',         price = 5000, amount = 50 },
        { name = 'thermite',          price = 5000, amount = 50 },
        { name = 'trojan_usb',        price = 5000, amount = 50 },
        { name = 'drill',             price = 5000, amount = 50 },
        { name = 'radioscanner',      price = 5000, amount = 50 },
        { name = 'cryptostick',       price = 5000, amount = 50 },
        { name = 'joint',             price = 5000, amount = 50 },
        { name = 'cokebaggy',         price = 5000, amount = 50 },
        { name = 'crack_baggy',       price = 5000, amount = 50 },
        { name = 'xtcbaggy',          price = 5000, amount = 50 },
        { name = 'coke_brick',        price = 5000, amount = 50 },
        { name = 'weed_brick',        price = 5000, amount = 50 },
        { name = 'coke_small_brick',  price = 5000, amount = 50 },
        { name = 'oxy',               price = 5000, amount = 50 },
        { name = 'meth',              price = 5000, amount = 50 },
        { name = 'weed_whitewidow',   price = 5000, amount = 50 },
        { name = 'weed_skunk',        price = 5000, amount = 50 },
        { name = 'weed_purplehaze',   price = 5000, amount = 50 },
        { name = 'weed_ogkush',       price = 5000, amount = 50 },
        { name = 'weed_amnesia',      price = 5000, amount = 50 },
        { name = 'weed_ak47',         price = 5000, amount = 50 },
        { name = 'markedbills',       price = 5000, amount = 50, info = { worth = 5000 } },
    },
    ['prison'] = {
        { name = 'sandwich',     price = 4, amount = 50 },
        { name = 'water_bottle', price = 4, amount = 50 },
    },
    ['police'] = {
        { name = 'weapon_pistol',       price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_stungun',      price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_pumpshotgun',  price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_smg',          price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_MACRO_02', label = '1x Scope' }, { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_carbinerifle', price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', label = '3x Scope' } } } },
        { name = 'weapon_nightstick',   price = 0, amount = 50 },
        { name = 'weapon_flashlight',   price = 0, amount = 50 },
        { name = 'pistol_ammo',         price = 0, amount = 50 },
        { name = 'smg_ammo',            price = 0, amount = 50 },
        { name = 'shotgun_ammo',        price = 0, amount = 50 },
        { name = 'rifle_ammo',          price = 0, amount = 50 },
        { name = 'handcuffs',           price = 0, amount = 50 },
        { name = 'empty_evidence_bag',  price = 0, amount = 50 },
        { name = 'police_stormram',     price = 0, amount = 50 },
        { name = 'armor',               price = 0, amount = 50 },
        { name = 'radio',               price = 0, amount = 50 },
        { name = 'heavyarmor',          price = 0, amount = 50 },
    },

     ['ambulance'] = {
        { name = 'radio',                   price = 0, amount = 50 },
        { name = 'bandage',                 price = 0, amount = 50 },
        { name = 'painkillers',             price = 0, amount = 50 },
        { name = 'firstaid',                price = 0, amount = 50 },
        { name = 'weapon_flashlight',       price = 0, amount = 50 },
        { name = 'weapon_fireextinguisher', price = 0, amount = 50 },
    },

}

Config.Locations = {

 ['ambulance'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(309.93, -602.94, 43.29, 71.0820),
        ['ped'] = 's_m_m_doctor_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(283.5821, -614.8570, 43.3792, 159.2903),
        ['requiredJob'] = 'ambulance'
    },

     ['police'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(461.8498, -981.0677, 30.6896, 91.5892),
        ['ped'] = 'mp_m_securoguard_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(459.0441, -1008.0366, 28.2627, 271.4695),
        ['requiredJob'] = 'police',
    },

        ['prison'] = {
        ['label'] = 'Canteen Shop',
        ['coords'] = vector4(1777.59, 2560.52, 44.62, 187.83),
        ['ped'] = false,
        ['products'] = Config.Products['prison'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1845.8175, 2585.9312, 45.6721, 96.7577)
    },

    ['blackmarket'] = {
        ['label'] = 'Black Market',
        ['coords'] = vector4(-594.7032, -1616.3647, 33.0105, 170.6846),
        ['ped'] = 'a_m_y_smartcaspat_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-clipboard',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['blackmarket'],
        ['delivery'] = vector4(-428.6385, -1728.1962, 19.7838, 75.6646)
    },
    -- 24/7 Locations
    ['247supermarket'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(24.47, -1346.62, 29.5, 271.66),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(26.45, -1315.51, 29.62, 0.07)
    },

    ['247supermarket13'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(462.8564, 5570.2227, 796.7745, 178.3608),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(462.8564, 5570.2227, 796.7745, 178.3608)
    },

    ['247supermarket2'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },

    ['247supermarket3'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },

    ['247supermarket4'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },

    ['247supermarket5'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },

    ['247supermarket6'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(549.13, 2670.85, 42.16, 99.39),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(541.54, 2663.53, 42.17, 120.51)
    },

    ['247supermarket7'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },

    ['247supermarket8'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2556.66, 380.84, 108.62, 356.67),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2553.24, 399.73, 108.56, 344.86)
    },

    ['247supermarket9'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(372.66, 326.98, 103.57, 253.73),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    ['247supermarket10'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(203.61, -1018.27, 29.73, 106.37),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    ['247supermarket11'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-1149.1063, -1701.2939, 4.5614, 303.1005),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1149.1063, -1701.2939, 4.5614, 303.1005)
    },

    ['247supermarket12'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(5876.7510, -4951.0708, 180.4831, 239.4829),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(5876.7510, -4951.0708, 180.4831, 239.4829)
    },
    
    ['247supermarket13'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(89.7962, 290.9756, 110.2074, 166.2778),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(89.7962, 290.9756, 110.2074, 166.2778)
    },

    -- LTD Gasoline Locations
    ['ltdgasoline'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-40.51, -1747.45, 29.29, 326.39)
    },

    ['ltdgasoline2'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-706.06, -913.97, 19.22, 88.04),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-702.89, -917.44, 19.21, 181.96)
    },

    ['ltdgasoline3'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },

    ['ltdgasoline4'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(1164.71, -322.94, 69.21, 101.72),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1160.62, -312.06, 69.28, 3.77)
    },

    ['ltdgasoline5'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['stores'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },

    -- Rob's Liquor Locations
    ['robsliquor'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },

    ['robsliquor2'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },

    ['robsliquor3'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },

    ['robsliquor4'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },

    ['robsliquor5'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(1134.2, -982.91, 46.42, 277.24),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    -- Hardware Store Locations
    ['hardware'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(45.68, -1749.04, 29.61, 53.13),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(89.15, -1745.29, 30.09, 315.25)
    },

    ['hardware2'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['hardware3'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },

    ['hardware4'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(-1644.3163, -988.3004, 13.0175, 230.5360),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1644.3163, -988.3004, 13.0175, 230.5360)
    },

    ['tuning3'] = {
        ['label'] = 'Bennys',
        ['coords'] = vector4(812.9003, -985.9775, 26.6379, 342.0805),
        ['ped'] = 'ig_benny',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Bennys',
        ['products'] = Config.Products['tuning'],
        ['showblip'] = true,
        ['blipsprite'] = 72,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 46,
        ['delivery'] = vector4(812.9003, -985.9775, 26.6379, 342.0805)
    },

    -- Ammunation Locations
    ['ammunation'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-1189.1383, -1784.7321, 4.3800, 241.4358),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 85,
        ['delivery'] = vector4(-1189.1383, -1784.7321, 4.3800, 241.4358)
    },
   

    -- Casino Locations
    ['casino'] = {
        ['label'] = 'Diamond Casino',
        ['coords'] = vector4(978.46, 39.07, 74.88, 64.0),
        ['ped'] = 'csb_tomcasino',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-coins',
        ['targetLabel'] = 'Buy Chips',
        ['products'] = Config.Products['casino'],
        ['showblip'] = true,
        ['blipsprite'] = 617,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(972.6, 9.22, 81.04, 233.38)
    },

    ['casinobar'] = {
        ['label'] = 'Casino Bar',
        ['coords'] = vector4(968.13, 29.85, 74.88, 208.86),
        ['ped'] = 'a_m_y_smartcaspat_01',
        ['scenario'] = 'WORLD_HUMAN_VALET',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wine-bottle',
        ['targetLabel'] = 'Open Casino Bar',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(937.16, 1.0, 78.76, 152.4)
    },

    -- Weedshop Locations
    ['weedshop'] = {
        ['label'] = 'Smoke On The Water',
        ['coords'] = vector4(1393.83, -170.19, 161.53, 358.92),
        ['ped'] = 'a_m_y_hippy_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-cannabis',
        ['targetLabel'] = 'Open Weed Shop',
        ['products'] = Config.Products['weedshop'],
        ['showblip'] = true,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1393.83, -170.19, 161.53, 358.92)
    },
    ['weedshop2'] = {
        ['label'] = 'Smoke On The Water',
        ['coords'] = vector4(-1142.7991, -1710.4034, 4.2570, 308.1373),
        ['ped'] = 'a_m_y_hippy_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-cannabis',
        ['targetLabel'] = 'Open Weed Shop',
        ['products'] = Config.Products['weedshop'],
        ['showblip'] = true,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1142.7991, -1710.4034, 4.2570, 308.1373)
    },

    -- Sea Word Locations
    ['seaword'] = {
        ['label'] = 'Sea Word',
        ['coords'] = vector4(-1687.03, -1072.18, 13.15, 52.93),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Sea Word',
        ['products'] = Config.Products['gearshop'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1674.18, -1073.7, 13.15, 333.56)
    },

    -- Leisure Shop Locations
    ['leisureshop'] = {
        ['label'] = 'Leisure Shop',
        ['coords'] = vector4(-1505.91, 1511.95, 115.29, 257.13),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Leisure Shop',
        ['products'] = Config.Products['leisureshop'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    ["petshop"] = {
        ["label"] = "Pet Shop",
        ["coords"] = vector4(563.4059, 2753.0125, 42.8773, 185.0398), --or vector4(-659.87, -936.46, 21.83, 130.04), --  for mlo https://www.gta5-mods.com/maps/
        ["ped"] = 'S_M_M_StrVend_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-paw",
        ["targetLabel"] = "Open Pet Shop",
        ["products"] = Config.Products["petshop"],
        ["showblip"] = true,
        ['blipsprite'] = 273,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(561.18, 2741.51, 42.87, 199.08)
    },

    ["cow"] = {
        ["label"] = "cow",
        ["coords"] = vector4(2432.3184, 4802.5278, 34.8240, 220.5716), --or vector4(-659.87, -936.46, 21.83, 130.04), --  for mlo https://www.gta5-mods.com/maps/
        ["ped"] = 'a_c_cow',
        ["scenario"] = "WORLD_COW_GRAZING",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-paw",
        ["targetLabel"] = "Vaca",
        ["products"] = Config.Products["leisureshop"],
        ["showblip"] = true,
        ['blipsprite'] = 684,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 31,
        ['delivery'] = vector4(2432.3184, 4802.5278, 34.8240, 220.5716)
    },

    ["fac01"] = {
        ["label"] = "Bahamas",
        ["coords"] = vector4(-1384.8691, -591.9738, 30.3195, 56.5425), --or vector4(-659.87, -936.46, 21.83, 130.04), --  for mlo https://www.gta5-mods.com/maps/
        ["ped"] = 'a_f_y_topless_01',
        ["scenario"] = "WORLD_HUMAN_DRINKING_CASINO_TERRACE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-paw",
        ["targetLabel"] = "Bahamas",
        ["products"] = Config.Products["facs"],
        ["showblip"] = true,
        ['blipsprite'] = 93,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 31,
        ['delivery'] = vector4(-1384.8691, -591.9738, 30.3195, 56.5425)
    },

    ["fac02"] = {
        ["label"] = "Lost MC",
        ["coords"] = vector4(988.2866, -94.8512, 74.8453, 220.4648), --or vector4(-659.87, -936.46, 21.83, 130.04), --  for mlo https://www.gta5-mods.com/maps/
        ["ped"] = 'g_f_y_lost_01',
        ["scenario"] = "WORLD_HUMAN_DRINKING_CASINO_TERRACE",
        ["radius"] = 2.0,
        ["targetIcon"] = "fas fa-paw",
        ["targetLabel"] = "Lost MC",
        ["products"] = Config.Products["facs"],
        ["showblip"] = true,
        ['blipsprite'] = 495,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 31,
        ['delivery'] = vector4(988.2866, -94.8512, 74.8453, 220.4648)
    },
}
